CI/CD setup for backend
SOMAS2021/SOMAS2021 pull request #1
Opened 2021-11-19 14:57 UTC by JaafarRammal

# Summary

Added GitHub actions for testing, linting, building, and releasing versions

## Additional Information

- Simple backend structure with a main file
- Makefile for different Go executions
- Github action to test, lint, build, triggered by PR and merge
- Github action to release, triggered by tag with regex `v*`
- Packages structure for agents, utils, tower

## Test Plan

- Since we can't test actions in branches, tested in a separate repo [here](https://github.com/SOMAS2021/CICD-scratch-repo)

2021-11-19 22:05 UTC, jzzheng22 requested changes
James did most of this for me lmfao

2021-11-19 22:05 UTC, jzzheng22 commented on Makefile
> +
```suggestion
```

2021-11-19 22:05 UTC, jzzheng22 commented on Makefile
> +
Not needed (see below)

2021-11-19 22:05 UTC, jzzheng22 commented on .github/workflows/main.yaml
> +          go get -u golang.org/x/lint/golint
This should use `golangci-lint`.

https://github.com/golangci/golangci-lint-action

2021-11-19 22:05 UTC, jzzheng22 commented on .github/PULL_REQUEST_TEMPLATE.md
> +Please provide a summary of the change.
```suggestion
Please provide a summary of the change. What does this PR do? What does it solve?
```

2021-11-19 22:05 UTC, jzzheng22 commented on .github/PULL_REQUEST_TEMPLATE.md
> +Auxiliary information goes here.
```suggestion
Auxiliary information and additional context for the change goes here.
```

2021-11-19 22:52 UTC, JaafarRammal commented on Makefile
> +	@golint -set_exit_status ${PKG_LIST}
I think the vscode extension lints by itself

2021-11-19 22:58 UTC, JaafarRammal commented on Makefile
> +	@cat cover.out >> coverage.txt
Makes a text file that we can write to an external server to view it but I didn't end up setting that. I'll just cat the cover.out for now, and use the suggestion on slack for coverage

2021-11-23 10:43 UTC, JaafarRammal commented on Makefile
> +	@golint -set_exit_status ${PKG_LIST}
@jzzheng22 golangci-lint run is failing on the git server when running the pipeline, any advice?

2021-11-23 10:51 UTC, JaafarRammal commented on packages/utils/README.md
> +<!-- Util packages -->
Will leave the READMEs for now because otherwise the folders don't show up, we can remove them when we start generating the docs?

2021-11-23 10:51 UTC, JaafarRammal commented on packages/utils/README.md
> +<!-- Util packages -->
Mainly to get the pipeline out, we can change the way folders are documented in another PR

2021-11-23 12:31 UTC, jzzheng22 submitted a review, later dismissed
LGTM (thanks again to James xoxo)

2021-11-23 12:35 UTC, jzzheng22 approved these changes
My changes look good to me :))))))))))))))))))))

2021-11-23 12:44 UTC, JaafarRammal commented
LGTM thanks Jason, future PRs will hopefully be less cumbersome

2021-11-23 12:45 UTC, merged