Add runtime timeout
SOMAS2021/SOMAS2021 pull request #117
Opened 2021-12-27 01:02 UTC by JaafarRammal

Add timeout in case of bugs like deadlocks or infinite loops to not kill the pipeline for 6 hours

2021-12-27 14:46 UTC, jzzheng22 requested changes

2021-12-27 14:46 UTC, jzzheng22 commented on .github/workflows/main.yaml
> +    timeout-minutes: 5
```suggestion
    timeout-minutes: 15
```

2021-12-27 15:06 UTC, jzzheng22 commented on .github/workflows/main.yaml
> +    timeout-minutes: 5
Actually idk if this is necessary

2021-12-27 23:59 UTC, JaafarRammal commented on .github/workflows/main.yaml
> +    timeout-minutes: 5
The timeout or the 15?

2021-12-28 00:11 UTC, jzzheng22 commented on .github/workflows/main.yaml
> +    timeout-minutes: 5
The 15

2021-12-28 00:26 UTC, JaafarRammal commented on .github/workflows/main.yaml
> +    timeout-minutes: 5
Let's put 10 hehe

2021-12-28 01:12 UTC, jzzheng22 approved these changes

2021-12-28 01:12 UTC, merged