Infra/propogate messages
SOMAS2021/SOMAS2021 pull request #190
Opened 2021-12-31 20:46 UTC by woonmoon

To talk to agents that are several floors away from you, the messages need to "propagate" in the correct direction.
When sending a message now please additionally specify the target floor e.g. for `AskFoodTakenMessage`s
`NewAskFoodTakenMessage(senderID uuid.UUID, senderFloor int, targetFloor int)`
Now in the `Visit` function, if the message's target floor is not equal to the agent's current floor, the agent's `HandlePropogate()` function will be called.

Of course, agents _should_ have the ability to lie, break the chain of communication or distort the message if they wanted to. However, in the "honest" iterations we assumed cooperation which meant:
- An agent does not tamper with the message as it relayed it forward
- An agent relays the message in the correct direction
- The agent does not store any information regarding a message that was not intended for him

`BaseAgent` has implemented an honest, cooperative `HandlePropogate()` function which politely sends a message in the correct direction. We ask that agent teams do not override this function in honest runs but you are welcome to override for other experiments.

(Team 6's (@MattScottEEE) message passing was slightly affected, I just added `a.Floor()+1` as a targetFloor field for one of your messages)

2021-12-31 21:18 UTC, JaafarRammal submitted a review, later dismissed

2022-01-01 13:22 UTC, jzzheng22 requested changes
Can we get rid of `direction` inside of `BaseAgent.SendMessage()`? I think it's really confusing - and it should be calculable from the message itself anyway.

2022-01-01 17:05 UTC, hussain2603 approved these changes
looks good. Thanks gowoon :)

2022-01-01 19:53 UTC, jzzheng22 approved these changes
Have tested briefly, looks good, we'll test it more thoroughly with our agents later.

2022-01-01 19:59 UTC, jzzheng22 approved these changes

2022-01-01 19:59 UTC, merged