[TEAM6] Rewrite treaties
SOMAS2021/SOMAS2021 pull request #289
Opened 2022-01-09 23:55 UTC by JaafarRammal

Proposing a cleaner treaty function code

2022-01-09 23:59 UTC, jzzheng22 approved these changes
Looks a lot cleaner, thanks

ideally put HP and AvailableFood in their own functions

2022-01-10 00:00 UTC, JaafarRammal commented
Doing this now

2022-01-10 00:11 UTC, jzzheng22 requested changes

2022-01-10 00:11 UTC, jzzheng22 commented on pkg/agents/team6/treaties.go
>  		case 1:
```suggestion
		case messages.HP:
```

2022-01-10 00:11 UTC, jzzheng22 commented on pkg/agents/team6/treaties.go
>  		case 2:
```suggestion
		case messages.Floor:
```

2022-01-10 00:11 UTC, jzzheng22 commented on pkg/agents/team6/treaties.go
>  		case 3:
```suggestion
		case messages.AvailableFood:
```

2022-01-10 00:23 UTC, jzzheng22 reviewed
much much cleaner, thanks

have added my own additional refactor as well

2022-01-10 00:39 UTC, jzzheng22 commented
@MattScottEEE  not really appropriate for me to review this given I wrote part of it, but I'm happy for this to go through. It's your team's branch though.

2022-01-10 00:39 UTC, jzzheng22 approved these changes

2022-01-10 00:40 UTC, MattScottEEE requested changes
Mat check this plz

2022-01-10 00:40 UTC, MattScottEEE commented on pkg/agents/team6/treaties.go
> +		return considerTreaty
```suggestion
```

2022-01-10 00:41 UTC, MattScottEEE commented on pkg/agents/team6/treaties.go
> +		return considerTreaty
```suggestion
```

2022-01-10 00:51 UTC, MattScottEEE approved these changes
Tested, LGTM - thanks Jaafar + Jason

2022-01-10 00:51 UTC, merged