Adding Random Agent
SOMAS2021/SOMAS2021 pull request #53
Opened 2021-12-14 17:46 UTC by Rhys-J

Adding an agent that takes a random amount of food between 0 and 100. Currently does nothing else.

# Summary

Solves #33. Creates a random agent for experimentation

## Additional Information

Random agent that only takes a food amount between 0 and 100. Does not sent messages

## Test Plan

Ran simulation and checked log files to see amount of food taken was random.

2021-12-14 18:29 UTC, JaafarRammal requested changes
Thanks for the agent! Just a minor rename comment otherwise LGTM

2021-12-14 18:29 UTC, JaafarRammal commented on pkg/agents/randomAgent/agent.go
> +package agentRandom
LGTM! Otherwise can we rename just to have consistency?
```suggestion
package randomAgent
```

2021-12-14 18:29 UTC, JaafarRammal commented on pkg/simulation/simulation.go
> +	agentRandom "github.com/SOMAS2021/SOMAS2021/pkg/agents/randomAgent"
```suggestion
	"github.com/SOMAS2021/SOMAS2021/pkg/agents/randomAgent"
```

2021-12-14 18:29 UTC, JaafarRammal commented on pkg/simulation/simulation.go
> +	abs := []AgentNewFunc{agent1.New, agent2.New, team6.New, agentRandom.New}
```suggestion
	abs := []AgentNewFunc{agent1.New, agent2.New, team6.New, randomAgent.New}
```

2021-12-15 15:33 UTC, udai-arneja commented
Try not to change default parameters in the main.go file when committing, I think its good practice not to because it can get confused with the actual change in the PR. Otherwise LGTM, thanks !

2021-12-15 18:49 UTC, merged