Infra gofmt linting
SOMAS2021/SOMAS2021 pull request #78
Opened 2021-12-23 01:57 UTC by JaafarRammal

# Summary

Enforce `gofmt` in pipeline

## Test Plan

The branch itself SMH

2021-12-23 15:00 UTC, jzzheng22 requested changes

2021-12-23 15:00 UTC, jzzheng22 commented on .github/PULL_REQUEST_TEMPLATE.md
> +*Pssst...you... yes you! Did you run `make lint` and perhaps `make format`?*
```suggestion
*Pssst...you... yes you! Did you run `make lint` and perhaps `make format`? If not, go away, run those commands, and then come back (if you are using VS Code... then you shouldn't need to do `make lint`*
```

2021-12-23 23:01 UTC, JaafarRammal commented on pkg/agents/team1/agent1/agent.go
> +
oops

2021-12-24 00:05 UTC, jzzheng22 approved these changes
LGTM, thanks

2021-12-24 00:44 UTC, merged